version: "3.9"

services:
  api:
    image: transaction
    ports:
    - "8080:8080"
    links:
    - db
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:16.0-alpine3.18
    environment:
      - POSTGRES_DB=transaction
      - POSTGRES_USER=local_development
      - POSTGRES_PASSWORD=local_development
    ports:
    - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U local_development -d transaction"]
      interval: 5s
      timeout: 3s
      retries: 10